version: '3.9'

services:
  
  traefik:
    image: traefik:v2.10
    restart: always
    container_name: traefik
    ports:
      - published: 443 # change here to 8443
        target: 443
        mode: host
      - published: 8050
        target: 8050
        mode: host
    command:
      - "--providers.docker=true"
      - "--providers.docker.network=tproxy"
      - "--providers.docker.exposedByDefault=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
      - "--entryPoints.web.http.redirections.entryPoint.scheme=https"
      - "--entryPoints.websecure.http.tls=true"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=chris@zignage.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.websecure.address=:443"
      - "--api.dashboard=true"
      - "--log.level=INFO"
      - "--accesslog=true"
      - "--api.debug=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--metrics.prometheus=true"
      - "--providers.docker.watch"
      - "--metrics.prometheus.buckets=0.1,0.3,1.2,5.0"
    volumes:
      - ./letsencrypt:/letsencrypt # Volume for certs (TLS)
      - /var/run/docker.sock:/var/run/docker.sock # Volume for docker admin
      - /home/zignage/traefik/supreme-carnival/.htpasswd:/.htpasswd
    networks:
      - tproxy
      - appnet
      - nginxrp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=myresolver"
      - "traefik.http.routers.traefik-ui.rule=Host(`${TRAEFIK_URL}`)"
      - "traefik.http.routers.traefik-ui.service=api@internal"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_BASIC_AUTH}"
      - "traefik.http.middlewares.traefik-auth.basicauth.removeheader=true"
      - "traefik.http.routers.traefik-ui.middlewares=traefik-auth"

  nginx-proxy:
    image: nginxproxy/nginx-proxy:latest
    container_name: nginx-proxy
    network_mode: host
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      HTTP_PORT: 3333
      HTTPS_PORT: 10333
      VIRTUAL_HOST: mender10.zignage.sobe.world
      VIRTUAL_PORT: 80
      #LETSENCRYPT_HOST: mender9.zignage.sobe.world
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginxp.rule=Host(`nginxrp10.zignage.sobe.world`)"
      - "traefik.http.routers.nginxp.entrypoints=websecure"
      - "traefik.http.services.nginxp.loadbalancer.server.port=3333"
      - "traefik.docker.network=tproxy"

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    environment:
      DEFAULT_EMAIL: raina@autistici.org
    depends_on:
      - nginx-proxy
    networks:
      - nginxrp

  whoami:
    image: traefik/whoami:latest
    ports:
      - "8033:8033"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mywhoami.rule=Host(`whoami9.zignage.sobe.world`)"
      - "traefik.http.routers.mywhoami.entrypoints=websecure"
      - "traefik.http.services.mywhoami.loadbalancer.server.port=8033"
      - "traefik.http.routers.mywhoami.tls.certresolver=myresolver"
      - "traefik.docker.network=tproxy"
    networks:
      - tproxy

        #grafana:
        # image: grafana/grafana:latest
        #user: root
        #volumes:
        # - ${GRAFANA_VOLUME}:/var/lib/grafana
        #- ./compose/grafana/provisioning/:/etc/grafana/provisioning
        #- ./infrastructure/config/grafana/grafana.ini:/etc/grafana/grafana.ini
        #- ./infrastructure/config/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
        # environment:
        #GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: "true"
        #GF_INSTALL_PLUGINS: grafana-piechart-panel
        #VIRTUAL_HOST: graf1.ztest.sobe.world
        #restart: unless-stopped
        #logging:
        #options:
        # max-size: "10m"
        # max-file: "3"     

  grafana:
    image: grafana/grafana:latest
    user: root
    container_name: grafana
    environment:
      GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: "true"
      GF_INSTALL_PLUGINS: grafana-piechart-panel
    ports:
      - "3000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`graf9.zignage.sobe.world`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.http.routers.grafana.middlewares=traefik-auth"
      - "traefik.http.routers.grafana.tls.certresolver=myresolver"
    volumes:
      - grafana-data:/var/lib/grafana
      #- ${GRAFANA_VOLUME}:/var/lib/grafana
    networks:
      - grafnet
      - appnet
      - tproxy
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus
    user: root
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ${PROM_VOLUME}:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.size=256MB'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`prom11.zignage.sobe.world`)"
      - "traefik.http.routers.prometheus.entrypoints=websecure"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
      - "traefik.http.routers.prometheus.middlewares=traefik-auth"
      - "traefik.http.routers.prometheus.tls.certresolver=myresolver"
      - "traefik.docker.network=tproxy"
    networks:
      - grafnet
      - appnet
      - tproxy
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"

          #  prometheus:
          #    image: prom/prometheus:latest
          #    user: root
          #    container_name: prometheus
          #    volumes:
          #      - ./prometheus:/etc/prometheus
          #      - prometheus_data:/prometheus
          #    command:
          #      - '--config.file=/etc/prometheus/prometheus.yml'
          #      - '--storage.tsdb.path=/prometheus'
          #      - '--web.console.libraries=/etc/prometheus/console_libraries'
          #      - '--web.console.templates=/etc/prometheus/consoles'
          #      - '--storage.tsdb.retention.time=200h'
          #      - '--storage.tsdb.retention.size=756MB'
          #      - '--web.enable-lifecycle'
          #    labels:
          #      - "traefik.enable=true"
          #      - "traefik.http.routers.prometheus.rule=Host(`prom11.zignage.sobe.world`)"
          #      - "traefik.http.routers.prometheus.entrypoints=websecure"
          #      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
          #      - "traefik.http.routers.prometheus.tls.certresolver=myresolver"
          #      - "traefik.http.routers.prometheus.middlewares=traefik-auth"
          #  - "traefik.docker.network=tproxy"
          # restart: unless-stopped
          #networks:
          #  - tproxy
          #  logging:
          # options:
          #    max-size: "10m"
          #    max-file: "3"
          # labels:
          #   org.label-schema.group: "monitoring"

  alertmanager:
    image: prom/alertmanager:v0.25.0
    container_name: alertmanager
    volumes:
      - ./alertmanager:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    restart: unless-stopped
    expose:
      - 9093
    networks:
      - appnet
      - tproxy
    labels:
      org.label-schema.group: "monitoring"

  nodeexporter:
    image: prom/node-exporter:latest
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    expose:
      - 9100
    networks:
      - appnet
      - tproxy
    labels:
      org.label-schema.group: "monitoring"

  mongodb:
    restart: always
    container_name: mongodb
    image: mongo:4.4.6
    tty: true
    env_file:
      - .env
    volumes:
      - ./meshcentral/mongodb_data:/data/db
    expose:
      - 27017
    networks:
      - meshcentral-tier

  meshcentral:
    restart: always
    container_name: meshcentral
    image: typhonragewind/meshcentral:latest
    depends_on:
      - mongodb
    ports:
      - 4430:4430
    volumes:
      - ./meshcentral/data:/opt/meshcentral/meshcentral-data
      - ./meshcentral/user_files:/opt/meshcentral/meshcentral-files
      - ./meshcentral/backup:/opt/meshcentral/meshcentral-backup
      - ./meshcentral/web:/opt/meshcentral/meshcentral-web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.meshcentral-secured.entrypoints=websecure"
      - "traefik.http.routers.meshcentral-secured.rule=Host(`mesh9.zignage.sobe.world`)"
      - "traefik.http.services.meshcentral.loadbalancer.server.port=4430"
      - "traefik.docker.network=tproxy"
    networks:
      - meshcentral-tier
      - tproxy
    environment:
      - HOSTNAME=mesh9.zignage.sobe.world     #your hostname
      - REVERSE_PROXY=localhost     #set to your reverse proxy IP if you want to put meshcentral behind a reverse proxy
      - REVERSE_PROXY_TLS_PORT=443
      - IFRAME=false    #set to true if you wish to enable iframe support
      - ALLOW_NEW_ACCOUNTS=true    #set to false if you want disable self-service creation of new accounts besides the first (admin)
      - WEBRTC=false  #set to true to enable WebRTC - per documentation it is not officially released with meshcentral, but is solid enough to work with. Use with caution
      - BACKUPS_PW=MyAwesomePasswordPleaseChangeMe #password for the autobackup function
      - BACKUP_INTERVAL=24 # Interval in hours for the autobackup function
      - BACKUP_KEEP_DAYS=10 #number of days of backups the function keeps
      - VIRTUAL_HOST=mesh9.zignage.sobe.world
      - VIRTUAL_PORT=4430
      - NODE_ENV=production
      - LETSENCRYPT_HOST=mesh9.zignage.sobe.world
      - LETSENCRYPT_EMAIL=ggmethos@autistici.org

networks:
  meshcentral-tier:
    name: meshcentral-tier
    driver: bridge
  tproxy:
    name: tproxy
  appnet:
    name: appnet
  nginxrp:
    name: nginxrp
  web:
    name: web
  grafnet:
    name: grafnet
    driver: bridge


volumes: 
  letsencrypt:
    name: letsencrypt
  certs:
  vhost:
  html:
  acme:
  grafana-data:
  prometheus_data: {}
  grafana_data: {}
