global:
  scrape_interval: 15s # Default is every 1 minute.
  evaluation_interval: 5s

rule_files:
  - /postgres.rules
  - /core.rules

alerting:
  alertmanagers:
    - static_configs:
      - targets: ["alertmanager:9093"]

scrape_configs:
#  - job_name: 'otel-collector'
#    honor_timestamps: true
#    scrape_interval: 10s
#    scrape_timeout: 5s
#    metrics_path: /metrics
#    scheme: http
#    static_configs:
#      - targets: ['otel-collector:9464']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']
  - job_name: 'node'
    static_configs:
      - targets: [ "node_exporter:9100" ]
  - job_name: 'players'
    static_configs:
      - targets: [  ]  
  - job_name: 'postgres'
    static_configs:
      - targets: [ "postgres_exporter:9187"]
  - job_name: 'traefik'
    static_configs:
      - targets: ['proxy:8080']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
